// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lddnxcfnbpklqcspjvrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZG54Y2ZuYnBrbHFjc3BqdnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDU2NDUsImV4cCI6MjA3MDEyMTY0NX0.ZEtrsm1UKP29gh1v3ojrvzOQZFFyxfrj70yjWS-N82s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});